name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.1

      - name: Add Helm repositories required to install dependencies
        run: |
          while read -r DEP_REPO; do
            helm repo add "${DEP_REPO//(https:\/\/|\/)/_}" "${DEP_REPO}"
          done < <(
            for CHART_DIR in $(find ./charts -mindepth 2 -maxdepth 2 -type f -name Chart.yaml -exec dirname {} \;); do
              if [ -f "${CHART_DIR}/Chart.lock" ]; then
                awk '/repository:/ {print $2}' "./${CHART_DIR}/Chart.lock"
              fi
            done | sort -u
          )

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: charts
          skip_existing: true
          mark_as_latest: true
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
