name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git for Chart Releaser
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: charts
          skip_existing: true
          mark_as_latest: true
          pages_branch: gh-pages
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
